baseURL: https://javiermedinamurua.github.io/
languageCode: en-uk
title: Javier Medina Murua

# disable taxonomy pages
taxonomies: []

permalinks:
  posts: /:year/:month/:title/

markup:
  goldmark:
    renderer:
      unsafe: true
  tableOfContents:
    startLevel: 1
    endLevel: 9
